server:
  port: 8084

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8083/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: gpsUtilsModule
          uri: http://localhost:8081/
          predicates:
            - Path=/test/**

        - id: rewardModule
          uri: http://localhost:8082/
          predicates:
              - Path=/testReward/**




