server:
  port: 8084

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://localhost:8083/eureka

spring:
  cloud:
    gateway:
      routes:
        - id: employeeModule
          uri: http://localhost:8081/
          predicates:
            - Path=/test/**
