server:
port: 8080

eureka:
client:
serviceUrl:
defaultZone: http://localhost:8083/eureka

spring:
application:
name: TourServiceGateway
cloud:
gateway:
routes:
  - id: employeeModule
  uri: lb://gpsUtils
  predicates:
  - Path=/test/**
  - id: consumerModule
uri: lb://Rewards
predicates:
  - Path=/test2/**
